image: fbe-dockerreg.rwu.de/adm-iki/systems/gitlab-runner-docker:master

stages:
    - docker

build_docker_image:
    stage: docker
    tags:
        - image-build
    script: 
    - docker build -t fbe-dockerreg.rwu.de/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:[VERSION] -f docker/Dockerfile .
    - docker push fbe-dockerreg.rwu.de/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:[VERSION]
