version: '2.4'
services:

#default container settings
  base:
    environment:
      DISPLAY: $DISPLAY
    network_mode: host
    privileged: true
    stdin_open: true
    command: tail -f /dev/null

#ros default settings
  ros:
    extends: base
    environment:
      WAIT_FOR_ROSCORE: 1
      ROS_IP: $ROS_IP
      ROS_HOSTNAME: $ROS_HOSTNAME
      ROS_MASTER_URI: $ROS_MASTER_URI

#nvidia stuff for using gpu
  ros_nvidia:
    extends: ros
    runtime: nvidia
    environment:
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority

#Usage:
###########################
# service:
#   extends:
#     file: common.yml
#     service: ros
