version: '2.4'
services:
  [REPO_NAME]:
    container_name: [REPO_NAME]
    extends:
      file: common.yml
      service: ros
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: tested
    image: [REPO_NAME]:[TAG]
